// --- Auto Generated By CodeGen Module ---
package com.luban.codegen.test.domain.mapper;

import com.luban.common.base.mapper.DateMapper;
import com.luban.common.base.mapper.GenericEnumMapper;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

/**
 * @author hp
 */
@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface TestOrderMapper {
  TestOrderMapper INSTANCE = Mappers.getMapper(TestOrderMapper.class);
}
