// --- Auto Generated By CodeGen Module ---
package com.hp.joininmemory.example.domain.order.response;

import com.hp.codegen.processor.response.AbstractBaseResponse;
import com.hp.common.base.annotations.FieldDesc;
import lombok.Data;

@Data
public class OrderResponse extends AbstractBaseResponse {
  @FieldDesc("订单号")
  private String orderNo;

  @FieldDesc("状态")
  private Integer status;
}
