// --- Auto Generated By CodeGen Module ---
package com.hp.codegen.test.domain.vo;

import lombok.Data;
import lombok.experimental.Accessors;

import java.io.Serializable;

@Data
@Accessors(
    chain = true
)
public class TestOrderVO implements Serializable {
  private String measureUnit;

  private String taxCategoryNo;

  private Long templateId;

  private String code;

  private String remark;

  private String skuName;
}
