// --- Auto Generated By CodeGen Module ---
package com.hp.joininmemory.example.domain.orderitem.service;

import com.hp.common.base.model.PageRequestWrapper;
import com.hp.joininmemory.example.domain.orderitem.request.OrderItemDTO;
import com.hp.joininmemory.example.domain.orderitem.response.OrderItemVO;
import org.springframework.data.domain.Page;

import java.util.List;

public interface IOrderItemService {
  Long createOrderItem(OrderItemDTO creator);

  void updateOrderItem(OrderItemDTO updater);

  void validOrderItem(Long id);

  void invalidOrderItem(Long id);

  OrderItemVO findById(Long id);

  Page<OrderItemVO> findByPage(PageRequestWrapper<OrderItemDTO> query);

  List<OrderItemVO> findAllByOrderIds(List<Long> orderIds);
}
