// --- Auto Generated By CodeGen Module ---
package com.luban.codegen.test.api.order.service;

import com.luban.codegen.test.api.order.request.TestOrderCreateRequest;
import com.luban.codegen.test.api.order.request.TestOrderPageRequest;
import com.luban.codegen.test.api.order.request.TestOrderUpdateRequest;
import com.luban.codegen.test.api.order.response.TestOrderPageResponse;
import com.luban.codegen.test.api.order.response.TestOrderResponse;
import com.luban.common.base.model.PageResponse;
import com.luban.common.base.model.Returns;
import java.lang.Long;
import java.lang.Void;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

/**
 * @author hp
 */
@FeignClient(
        value = "orderServer",
        contextId = "testOrderClient",
        path = "testOrder/v1"
)
public interface TestOrderFeignService {
    @PostMapping("create")
    Returns<Long> createTestOrder(@RequestBody TestOrderCreateRequest request);

    @PostMapping("update")
    Returns<Void> updateTestOrder(@RequestBody TestOrderUpdateRequest request);

    @PostMapping("enable/{id}")
    Returns<Void> enableTestOrder(@PathVariable("id") Long id);

    @PostMapping("disable/{id}")
    Returns<Void> disableTestOrder(@PathVariable("id") Long id);

    @GetMapping("findById/{id}")
    Returns<TestOrderResponse> findById(@PathVariable("id") Long id);

    @PostMapping("findByPage")
    Returns<PageResponse<TestOrderPageResponse>> findByPage(
            @RequestBody TestOrderPageRequest request);
}
