// --- Auto Generated By CodeGen Module ---
package com.luban.codegen.test.domain.service;

import com.luban.codegen.test.domain.TestOrder;
import java.lang.Long;
import java.util.Collection;
import java.util.List;

/**
 * @author hp
 */
public interface ITestOrderService {
  void enableTestOrder(Long id);

  void disableTestOrder(Long id);

  TestOrder findById(Long id);

  List<TestOrder> findAllById(Collection<Long> ids);
}
