// --- Auto Generated By CodeGen Module ---
package com.hp.joininmemory.example.domain.orderitem.repository;

import com.hp.joininmemory.example.domain.orderitem.OrderItem;
import com.hp.jpa.BaseRepository;
import java.lang.Long;

public interface OrderItemRepository extends BaseRepository<OrderItem, Long> {
}
