// --- Auto Generated By CodeGen Module ---
package com.luban.codegen.test.domain.command;

import com.luban.codegen.test.domain.TestOrder;
import com.luban.common.base.annotations.FieldDesc;
import com.luban.common.base.command.CommandForUpdateById;
import com.luban.common.base.enums.ValidStatus;
import java.lang.Long;
import java.util.Optional;
import lombok.Data;

/**
 * @author hp
 */
@Data
public class UpdateTestOrderCommand implements CommandForUpdateById<Long> {
    private Long id;

    @FieldDesc("状态")
    private ValidStatus status;

    public void updateTestOrder(TestOrder source) {
        Optional.ofNullable(this.getStatus()).ifPresent(source::setStatus);
    }
}
