// --- Auto Generated By CodeGen Module ---
package com.hp.joininmemory.example.domain.order.mapper;

import com.hp.common.base.mapper.DateMapper;
import com.hp.common.base.mapper.GenericEnumMapper;
import com.hp.joininmemory.example.domain.order.Order;
import com.hp.joininmemory.example.domain.order.domainservice.model.OrderModel;
import com.hp.joininmemory.example.domain.order.request.OrderDTO;
import com.hp.joininmemory.example.domain.order.request.OrderRequest;
import com.hp.joininmemory.example.domain.order.response.OrderResponse;
import com.hp.joininmemory.example.domain.order.response.OrderVO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper(
        uses = {
                GenericEnumMapper.class,
                DateMapper.class
        }
)
public interface OrderMapper {
    OrderMapper INSTANCE = Mappers.getMapper(OrderMapper.class);

    Order dtoToEntity(OrderDTO dto);

    OrderDTO requestToDto(OrderRequest request);

    OrderResponse voToResponse(OrderVO vo);

    @Mapping(target = "orderId", source = "id")
    OrderModel voToModel(OrderVO vo);
}
