// --- Auto Generated By CodeGen Module ---
package com.hp.codegen.test.domain.service;

import com.hp.codegen.test.api.order.request.TestOrderPageRequest;
import com.hp.codegen.test.api.order.response.TestOrderPageResponse;
import com.hp.codegen.test.domain.TestOrder;
import com.hp.codegen.test.domain.command.CreateTestOrderCommand;
import com.hp.codegen.test.domain.command.UpdateTestOrderCommand;
import com.hp.common.base.model.PageRequestWrapper;
import com.hp.common.base.model.PageResponse;
import java.lang.Long;
import java.util.Collection;
import java.util.List;

/**
 * @author hp
 */
public interface ITestOrderService {
    Long createTestOrder(CreateTestOrderCommand command);

    void updateTestOrder(UpdateTestOrderCommand command);

    void enableTestOrder(Long id);

    void disableTestOrder(Long id);

    TestOrder findById(Long id);

    List<TestOrder> findAllById(Collection<Long> ids);

    PageResponse<TestOrderPageResponse> findByPage(
            PageRequestWrapper<TestOrderPageRequest> requestWrapper);
}
