// --- Auto Generated By CodeGen Module ---
package com.luban.codegen.test.domain.events;

import com.luban.codegen.test.domain.TestOrder;
import com.luban.codegen.test.domain.command.CreateTestOrderCommand;
import com.luban.codegen.test.domain.command.UpdateTestOrderCommand;
import com.luban.codegen.test.domain.context.CreateTestOrderContext;
import com.luban.codegen.test.domain.context.UpdateTestOrderContext;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * @author hp
 */
@Slf4j
@Component
@RequiredArgsConstructor
@Transactional(
        rollbackFor = Exception.class
)
public class TestOrderEventProcessor {
    @EventListener
    public void handleTestOrderCreated(TestOrderEvents.TestOrderCreatedEvent event) {
        final CreateTestOrderContext context = event.getContext();
        final TestOrder entity = context.getEntity();
        final CreateTestOrderCommand command = context.getCommand();
        // handle event
    }

    @EventListener
    public void handleTestOrderUpdated(TestOrderEvents.TestOrderUpdatedEvent event) {
        final UpdateTestOrderContext context = event.getContext();
        final TestOrder entity = context.getEntity();
        final UpdateTestOrderCommand command = context.getCommand();
        // handle event
    }
}
