// --- Auto Generated By CodeGen Module ---
package com.luban.codegen.test.api.order.request;

import com.luban.common.base.annotations.FieldDesc;
import com.luban.common.base.model.Request;
import java.lang.Integer;
import java.lang.Long;
import lombok.Data;

/**
 * @author hp
 */
@Data
public class TestOrderUpdateRequest implements Request {
    private Long id;

    @FieldDesc("状态")
    private Integer status;
}
