// --- Auto Generated By CodeGen Module ---
package com.hp.codegen.test.domain.command;

import com.hp.common.base.annotations.FieldDesc;
import com.hp.common.base.command.CommandForCreate;
import com.hp.common.base.enums.ValidStatus;
import lombok.Data;

/**
 * @author hp
 */
@Data
public class CreateTestOrderCommand implements CommandForCreate {
    @FieldDesc("状态")
    private ValidStatus status;
}
