// --- Auto Generated By CodeGen Module ---
package com.luban.codegen.test.domain.repository;

import com.luban.codegen.test.domain.TestOrder;
import com.luban.jpa.BaseRepository;
import java.lang.Long;
import org.springframework.stereotype.Repository;

/**
 * @author hp
 */
@Repository
public interface TestOrderRepository extends BaseRepository<TestOrder, Long> {
}
