// --- Auto Generated By CodeGen Module ---
package com.hp.joininmemory.example.domain.order.request;

import com.hp.codegen.processor.request.AbstractBaseRequest;
import com.hp.common.base.annotations.FieldDesc;
import java.lang.Integer;
import java.lang.String;
import lombok.Data;

@Data
public class OrderRequest extends AbstractBaseRequest {
  @FieldDesc("订单号")
  private String orderNo;

  @FieldDesc("状态")
  private Integer status;
}
