// --- Auto Generated By CodeGen Module ---
package com.hp.joininmemory.example.domain.orderitem.mapper;

import com.hp.common.base.mapper.DateMapper;
import com.hp.common.base.mapper.GenericEnumMapper;
import com.hp.joininmemory.example.domain.orderitem.OrderItem;
import com.hp.joininmemory.example.domain.orderitem.request.OrderItemDTO;
import com.hp.joininmemory.example.domain.orderitem.request.OrderItemRequest;
import com.hp.joininmemory.example.domain.orderitem.response.OrderItemResponse;
import com.hp.joininmemory.example.domain.orderitem.response.OrderItemVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface OrderItemMapper {
  OrderItemMapper INSTANCE = Mappers.getMapper(OrderItemMapper.class);

  OrderItem dtoToEntity(OrderItemDTO dto);

  OrderItemDTO requestToDto(OrderItemRequest request);

  OrderItemResponse voToResponse(OrderItemVO vo);
}
