// --- Auto Generated By CodeGen Module ---
package com.hp.codegen.test.domain.events;

import com.hp.codegen.test.domain.context.CreateTestOrderContext;
import com.hp.codegen.test.domain.context.UpdateTestOrderContext;
import lombok.Value;

/**
 * @author hp
 */
public interface TestOrderEvents {
    @Value
    class TestOrderCreatedEvent {
        CreateTestOrderContext context;
    }

    @Value
    class TestOrderUpdatedEvent {
        UpdateTestOrderContext context;
    }
}
