// --- Auto Generated By CodeGen Module ---
package com.hp.joininmemory.example.domain.orderitem.request;

import com.hp.codegen.processor.request.AbstractBaseRequest;
import com.hp.common.base.annotations.FieldDesc;
import lombok.Data;

@Data
public class OrderItemRequest extends AbstractBaseRequest {
  @FieldDesc("订单id")
  private Long orderId;

  @FieldDesc("状态")
  private Integer status;
}
