// --- Auto Generated By CodeGen Module ---
package com.hp.joininmemory.example.domain.orderitem.response;

import com.hp.codegen.processor.response.AbstractBaseResponse;
import com.hp.common.base.annotations.FieldDesc;
import lombok.Data;

@Data
public class OrderItemResponse extends AbstractBaseResponse {
  @FieldDesc("订单id")
  private String orderId;

  @FieldDesc("状态")
  private Integer status;
}
