// --- Auto Generated By CodeGen Module ---
package com.hp.codegen.test.api.order.request;

import com.hp.common.base.annotations.FieldDesc;
import com.hp.common.base.model.Request;
import java.lang.Integer;
import lombok.Data;

/**
 * @author hp
 */
@Data
public class TestOrderCreateRequest implements Request {
    @FieldDesc("状态")
    private Integer status;
}
