// --- Auto Generated By CodeGen Module ---
package com.hp.codegen.test.domain.context;

import com.hp.codegen.test.domain.TestOrder;
import com.hp.codegen.test.domain.command.UpdateTestOrderCommand;
import com.hp.common.base.context.AbstractContext;
import java.lang.Long;
import lombok.Getter;
import lombok.Setter;

/**
 * @author hp
 */
public class UpdateTestOrderContext extends AbstractContext<TestOrder, UpdateTestOrderCommand> {
    @Getter
    @Setter
    private Long updatedBy;

    public UpdateTestOrderContext(UpdateTestOrderCommand command) {
        super(command);
    }

    public static UpdateTestOrderContext create(UpdateTestOrderCommand command) {
        final UpdateTestOrderContext context = new UpdateTestOrderContext(command);
        context.init();
        return context;
    }

    private void init() {
    }
}
