// --- Auto Generated By CodeGen Module ---
package com.luban.codegen.test.domain.context;

import com.luban.codegen.test.domain.TestOrder;
import com.luban.codegen.test.domain.command.CreateTestOrderCommand;
import com.luban.common.base.context.AbstractContext;
import java.lang.Long;
import lombok.Getter;
import lombok.Setter;

/**
 * @author hp
 */
public class CreateTestOrderContext extends AbstractContext<TestOrder, CreateTestOrderCommand> {
    @Getter
    @Setter
    private Long createdBy;

    public CreateTestOrderContext(CreateTestOrderCommand command) {
        super(command);
    }

    public static CreateTestOrderContext create(CreateTestOrderCommand command) {
        final CreateTestOrderContext context = new CreateTestOrderContext(command);
        context.init();
        return context;
    }

    private void init() {
    }
}
