// --- Auto Generated By CodeGen Module ---
package com.hp.joininmemory.example.domain.order.repository;

import com.hp.joininmemory.example.domain.order.Order;
import com.hp.jpa.BaseRepository;

import java.util.Optional;

public interface OrderRepository extends BaseRepository<Order, Long> {
    default Optional<Order> findByOrderNo(String orderNo){
        final Order dummyOrder = new Order();
        dummyOrder.setOrderNo(orderNo);
        dummyOrder.valid();
        return Optional.of(dummyOrder);
    }
}
